# Generated by Django 3.2.11 on 2022-01-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
