# Generated by Django 3.2.11 on 2022-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220107_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
