# Generated by Django 3.2.11 on 2022-01-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220107_0242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new',
            new_name='new1',
        ),
    ]
