# Generated by Django 3.2.11 on 2022-01-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_new_new1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new1',
            new_name='akm',
        ),
    ]
